### ISSUE TITLE
Volatility returning wrong value

### ISSUE THREAD

**Issue by brunohkbx** [Codeminer42/cm42-central-support#1]
When tried  to calculate volatility with the following parameters result in a zero division.
Group_by_velocity.values = [0, 2]
Number_of_iterations = 10

The NaN value is a result of a zero division in the variance method at line 16.
Https://github.com/Codeminer42/cm42-central-support/blob/master/lib/central/support/statistics.rb#L16

Most probably it's calculating the wrong value of volatility so far.

Issue based on https://rollbar.com/cm42-central-bot/cm42-central-bot/items/15/

**Comment by akitaonrails** [comment]
Hm, this seems to happen because slice_non_zero removes the velocity 0 in the group_by_velocity ([0,2]) resulting in a slice of size 1. than the highlighted line does 1 - 1 resulting in 0. So maybe a fix should be:

```ruby
total = slice > 1 && (total(slice) < total(enumerable)) ? total(slice) - 1 : sample_size
```

**Comment by brunohkbx** [comment]
It doesn't work.
In the case when velocities is [0, 2] the slice will be [2.0] and will crash because an array doesn't have the method >.
We could manage to fix this isolate case taking the value out of the array, but suppose if the velocities is [0, 2, 0, 2] the slice method will return [2.0, 2.0]
